### ISSUE TITLE
Running Inference on a trained model

### ISSUE THREAD

**Issue by HasarinduPerera** [dobro12/CPO#3]
How can I inference a trained model?

I tried the code below, but it did not work. I cannot find what is the issue.

```
import torch
import argparse
from env import Env
from agent import Agent

def inference(saved_model_path, num_episodes):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    seed = 10
    max_ep_len = 1000
    max_steps = 4000
    
    # Load the trained agent and its checkpoint
    loaded_checkpoint = torch.load(saved_model_path, map_location=device)
    
    env_name = "Safexp-PointGoal1-v0"
    env = Env(env_name, seed, max_ep_len)

    args = {
        'agent_name':'CPO',
        'save_name':'',
        'discount_factor':0.99,
        'hidden1':512,
        'hidden2':512,
        'v_lr':2e-4,
        'cost_v_lr':2e-4,
        'value_epochs':200,
        'batch_size':10000,
        'num_conjugate':10,
        'max_decay_num':10,
        'line_decay':0.8,
        'max_kl':0.001,
        'damping_coeff':0.01,
        'gae_coeff':0.97,
        'cost_d':25.0/1000.0,
    }
    
    # Initialize the agent with the necessary arguments
    agent = Agent(env, device, args)
    
    agent.policy.load_state_dict(loaded_checkpoint['policy'])
    agent.value.load_state_dict(loaded_checkpoint['value'])
    agent.cost_value.load_state_dict(loaded_checkpoint['cost_value'])
    
    for _ in range(num_episodes):
        state = env.reset()
        total_reward = 0
        
        for step in range(max_steps):
            state_tensor = torch.tensor(state, device=device, dtype=torch.float)
            action_tensor, _ = agent.getAction(state_tensor, is_train=False)
            action = action_tensor.detach().cpu().numpy()
            
            next_state, reward, done, _ = env.step(action)
            total_reward += reward
            
            state = next_state
            
            if done:
                print(f"Episode reward: {total_reward}")
                break

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Inference using a saved model')
    parser.add_argument('saved_model_path', type=str, help='Path to the saved model checkpoint')
    parser.add_argument('--num_episodes', type=int, default=10, help='Number of episodes for inference')
    args = parser.parse_args()
    
    inference(args.saved_model_path, args.num_episodes)


```
Error:

```
Traceback (most recent call last):
  File "inference.py", line 69, in <module>
    inference(args.saved_model_path, args.num_episodes)
  File "inference.py", line 39, in inference
    agent = Agent(env, device, args)
  File ".../CPO/torch/agent.py", line 84, in __init__
    self.load()
  File ".../CPO/torch/agent.py", line 367, in load
    os.makedirs(self.checkpoint_dir)
  File ".../anaconda3/envs/cpo-only-env/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/checkpoint'
```

TIA

**Comment by dobro12** [comment]
I think you need to comment out the 84 line in "torch/agent.py" file (which is "self.load()" code).
I don't know which system you run the code, but in the load function of agent.py, you need to create new directory, but the system has no permission on making directories according to your error log...

**Comment by HasarinduPerera** [comment]
Hi, Thank you for your response. It worked!
